### ISSUE TITLE
How might the Partnership-Playbook incorporate consulting tactics or articulate that this playbook focuses on Delivery?

### ISSUE THREAD

**Issue by jtag** [18F/partnership-playbook#2]

**Comment by brethauer** [comment]
@jtag thank you for raising this! In the short term (now) I'll add some language to the intro paragraph, e.g. "This guide will help you, as an agency, understand what it’s like to work with the 18F Delivery team." 

I personally think it'd be valuable to articulate consulting tactics - and am personally agnostic about whether they live here or in their own playbook.  What are consulting's goals with publishing them? (for delivery for example a big goal was having a written record of principles we could share during intake with potential partners, in order to hold ourselves & clients accountable to them)
cc @wslack and @StephanieRivera

**Comment by wslack** [comment]
Also, this is based on lessons we've learned in past work - and articulated in a way to help us avoid any surprises in these areas.

**Comment by brethauer** [comment]
@jtag title and links have been changed to: "18F Delivery: Partnership Playbook" for now

**Comment by jtag** [comment]
Cool! And inspiring to draft out what we've learned the last year in
consulting for working with partners. A lot of overlap of course (we all
have the same core philosophies) just we deliver some other different
things.

Cheers.

On Thursday, October 29, 2015, Nick Brethauer notifications@github.com
wrote:

> @jtag https://github.com/jtag title and links have been changed to:
> "18F Delivery: Partnership Playbook" for now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/Partnership-Playbook/issues/2#issuecomment-152179962
> .

## 

Jesse Taggert
Director of Experience Design & Product Strategy Practices
18F Consulting  | GSA
cell: 415-730-4965
_https://18f.gsa.gov/consulting/ https://18f.gsa.gov/consulting/_

**Comment by awfrancisco** [comment]
Closing since the playbook is no longer only about delivery.
