### ISSUE TITLE
Feedback from a candidate - why not Java?

### ISSUE THREAD

**Issue by wslack** [18F/partnership-playbook#24]
Java has a strong developer community; we don't we include that on our languages page? JVM, etc etc.

**Comment by hollyallen** [comment]
While Java (and .NET, C, and C++) have strong developer communities, they are not currently in our stable of competencies. Ruby, Python, JavaScript, and Go have proven sufficient for the needs of our partner projects. Since we do mostly greenfield development, integrate with existing systems through APIs, and are not large enough to support all the languages, we are not currently inclined to support more of them.

**Comment by wslack** [comment]
Sent link to issue, closing this for now!
